seqname: Test_Seq_LQCD
jobs:
    A:
        walltime: "20:00:00"
        nodes: "500"
        partition: "gres1&gres2"
        command: |+
            for i in {1..20}; do
                export A="____"
                
            done
    B:
        walltime: "20:00:00"
        nodes: "3000"
        partition: "gres1&gres2"
        command: |+
            aaaaaaaa 
            bbbbbb
    C:
        walltime: "20:00:00"
        nodes: "3000"
        partition: "gres1&gres2"
        command: |+
            aaaaaaaa 
            bbbbbb
sequence:
    A: B
    C: B
