seqname: Test_Seq_LQCD
jobs:
    nt12b6793:
        time: "20:00:00"
        nodes: 500
        partition: "atlas1%atlas2"
        queue: "batch"
        output: "oe"
        command: |+
            for i in {1..20}; do
                export A="____"
            done
    nt12b6794:
        time: "20:00:00"
        nodes: 3000
        partition: "atlas1%atlas2"
        queue: "batch"
        output: "oe"
        command: |+
            export PMI_NO_FORK=1
            export CRAY_CUDA_MPS=1

            cd $PBS_O_WORKDIR
            date

            conf_num=0
            echo "Hello"

            for i in {0..31}
            do
            aprun -n 12 -N 1 ./wrapper1.sh $((i*12+conf_num*396)) &
            sleep 2s
            done
            aprun -n 12 -N 1 ./wrapper1.sh $((384+conf_num*396))
sequence:
    nt12b6793: nt12b6794
